# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-HTML-W3C
version:      0.01
version_from: lib/Test/HTML/W3C.pm
installdirs:  site
requires:
    Test::Builder::Module:         
    WebService::Validator::HTML::W3C: 0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
